In [1]:
import pandas as pd

movies = pd.read_csv('data/movies_w.csv')
movies.columns = ['movie_id','title','genres','year']

ratings = pd.read_csv('data/ratings_w.csv')

users = pd.read_csv('data/users_w.csv')
users.columns = ['user_id','gender','age','occupation','zip_code']

In [2]:
df = pd.merge(ratings, users, how='left', on='user_id')    # 'user_id','gender','age','occupation','zip_code'
df = pd.merge(df, movies, how='left', on='movie_id')       #  'movie_id','title','genres','year'
df

,user_id,movie_id,rating,time,gender,age,occupation,zip_code,title,genres,year
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama,1975
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical,1996
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance,1964
3,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama,2000
4,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy,1998
...,...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,956716541,M,25,6,11106,Weekend at Bernie's (1989),Comedy,1989
1000205,6040,1094,5,956704887,M,25,6,11106,"Crying Game, The (1992)",Drama|Romance|War,1992
1000206,6040,562,5,956704746,M,25,6,11106,Welcome to the Dollhouse (1995),Comedy|Drama,1995
1000207,6040,1096,4,956715648,M,25,6,11106,Sophie's Choice (1982),Drama,1982
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,1982

In [3]:
occupation = df['occupation']
occ = []

for x in occupation:
    if x==7:
        occ.append('CEO')
    elif x == 1:
        occ.append('교육자')
    elif (x == 0) | (x == 18):
        occ.append('기타')
    elif x == 8:
        occ.append('농부')
    elif x == 10:
        occ.append('미성년자')
    elif (x == 4) | (x==9) | (x==13) | (x==19):
        occ.append('비급여')
    elif (x == 2) | (x == 20) :
        occ.append('예술')
    elif (x == 12) |(x == 15)|(x == 17):
        occ.append('이공계_직장인')
    elif (x == 3) |(x == 5)|(x == 14):
        occ.append('인문계_직장인')
    elif (x == 16):
        occ.append('자영업자')
    else:
        occ.append('전문직')
    
df['occupation2'] = occ

In [4]:
year = df['year']
new = []

for x in year:
    if (x >= 1919) & (x < 1920):
        new.append('1910s')
    elif (x >= 1920) & (x < 1930):
        new.append('1920s')
    elif (x >= 1930) & (x < 1940):
        new.append('1930s')
    elif (x >= 1940) & (x < 1950):
        new.append('1940s')
    elif (x >= 1950) & (x < 1960):
        new.append('1950s')
    elif (x >= 1960) & (x < 1970):
        new.append('1960s')
    elif (x >= 1970) & (x < 1980):
        new.append('1970s')
    elif (x >= 1980) & (x < 1990):
        new.append('1980s')
    elif (x >= 1990) & (x < 2000):
        new.append('1990s')
    else:
        new.append('2000s')
df['year2'] = new

In [5]:
df

,user_id,movie_id,rating,time,gender,age,occupation,zip_code,title,genres,year,occupation2,year2
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama,1975,미성년자,1970s
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical,1996,미성년자,1990s
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance,1964,미성년자,1960s
3,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama,2000,미성년자,2000s
4,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy,1998,미성년자,1990s
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,956716541,M,25,6,11106,Weekend at Bernie's (1989),Comedy,1989,전문직,1980s
1000205,6040,1094,5,956704887,M,25,6,11106,"Crying Game, The (1992)",Drama|Romance|War,1992,전문직,1990s
1000206,6040,562,5,956704746,M,25,6,11106,Welcome to the Dollhouse (1995),Comedy|Drama,1995,전문직,1990s
1000207,6040,1096,4,956715648,M,25,6,11106,Sophie's Choice (1982),Drama,1982,전문직,1980s
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,1982,전문직,1980s

In [6]:
gens = ['Action','Adventure','Animation',
        "Children's",'Comedy','Crime','Documentary','Drama',
        'Fantasy',   'Film-Noir',   'Horror',   'Musical',   'Mystery',   
        'Romance',   'Sci-Fi',   'Thriller',   'War'   ,'Western']
ages = ['1910s','1920s','1930s','1940s','1950s','1960s','1970s','1980s','1990s','2000s']
occ = ['CEO', '교육','기타','농부','미성년자','비급여','예술','이공계_직장인','인문계_직장인','자영업자','전문직']

In [7]:
values = []

for i in gens:
    for j in ages:
        for a in occ:
            x = df[(df['genres'].str.contains(i)) & (df['year2']==j) & (df['occupation2']==a)]['rating'].mean()
            values.append((i,j,a,x))

In [8]:
values

[('Action', '1910s', 'CEO', nan),
 ('Action', '1910s', '교육', nan),
 ('Action', '1910s', '기타', nan),
 ('Action', '1910s', '농부', nan),
 ('Action', '1910s', '미성년자', nan),
 ('Action', '1910s', '비급여', 5.0),
 ('Action', '1910s', '예술', 3.0),
 ('Action', '1910s', '이공계_직장인', nan),
 ('Action', '1910s', '인문계_직장인', nan),
 ('Action', '1910s', '자영업자', nan),
 ('Action', '1910s', '전문직', 1.0),
 ('Action', '1920s', 'CEO', 3.75),
 ('Action', '1920s', '교육', nan),
 ('Action', '1920s', '기타', 4.333333333333333),
 ('Action', '1920s', '농부', nan),
 ('Action', '1920s', '미성년자', 1.5),
 ('Action', '1920s', '비급여', 4.0),
 ('Action', '1920s', '예술', 3.923076923076923),
 ('Action', '1920s', '이공계_직장인', 3.5),
 ('Action', '1920s', '인문계_직장인', 3.6666666666666665),
 ('Action', '1920s', '자영업자', 4.2),
 ('Action', '1920s', '전문직', 2.0),
 ('Action', '1930s', 'CEO', 3.6818181818181817),
 ('Action', '1930s', '교육', nan),
 ('Action', '1930s', '기타', 3.7828947368421053),
 ('Action', '1930s', '농부', 4.0),
 ('Action', '1930s', '미성년자', 3.75),
 ('Action', '1930s', '비급여', 3.63125),
 ('Action', '1930s', '예술', 3.832116788321168),
 ('Action', '1930s', '이공계_직장인', 3.8224852071005917),
 ('Action', '1930s', '인문계_직장인', 3.7131782945736433),
 ('Action', '1930s', '자영업자', 3.986842105263158),
 ('Action', '1930s', '전문직', 3.6578947368421053),
 ('Action', '1940s', 'CEO', 3.361111111111111),
 ('Action', '1940s', '교육', nan),
 ('Action', '1940s', '기타', 3.40625),
 ('Action', '1940s', '농부', nan),
 ('Action', '1940s', '미성년자', nan),
 ('Action', '1940s', '비급여', 3.875),
 ('Action', '1940s', '예술', 3.764705882352941),
 ('Action', '1940s', '이공계_직장인', 3.3513513513513513),
 ('Action', '1940s', '인문계_직장인', 3.5),
 ('Action', '1940s', '자영업자', 3.25),
 ('Action', '1940s', '전문직', 3.1333333333333333),
 ('Action', '1950s', 'CEO', 4.052738336713996),
 ('Action', '1950s', '교육', nan),
 ('Action', '1950s', '기타', 3.987975951903808),
 ('Action', '1950s', '농부', 3.857142857142857),
 ('Action', '1950s', '미성년자', 3.847457627118644),
 ('Action', '1950s', '비급여', 3.9404990403071016),
 ('Action', '1950s', '예술', 4.087155963302752),
 ('Action', '1950s', '이공계_직장인', 4.091040462427745),
 ('Action', '1950s', '인문계_직장인', 4.010498687664042),
 ('Action', '1950s', '자영업자', 4.081818181818182),
 ('Action', '1950s', '전문직', 4.003690036900369),
 ('Action', '1960s', 'CEO', 3.9819548872180452),
 ('Action', '1960s', '교육', nan),
 ('Action', '1960s', '기타', 3.9270568278201865),
 ('Action', '1960s', '농부', 3.4),
 ('Action', '1960s', '미성년자', 4.074380165289257),
 ('Action', '1960s', '비급여', 3.9083700440528633),
 ('Action', '1960s', '예술', 3.908127208480565),
 ('Action', '1960s', '이공계_직장인', 3.9500901984365604),
 ('Action', '1960s', '인문계_직장인', 3.8756169792694966),
 ('Action', '1960s', '자영업자', 3.912350597609562),
 ('Action', '1960s', '전문직', 3.96309963099631),
 ('Action', '1970s', 'CEO', 3.8560747663551402),
 ('Action', '1970s', '교육', nan),
 ('Action', '1970s', '기타', 3.7930825242718447),
 ('Action', '1970s', '농부', 3.640625),
 ('Action', '1970s', '미성년자', 3.9587628865979383),
 ('Action', '1970s', '비급여', 3.8276844203930502),
 ('Action', '1970s', '예술', 3.820282413350449),
 ('Action', '1970s', '이공계_직장인', 3.836712208021155),
 ('Action', '1970s', '인문계_직장인', 3.848193697156034),
 ('Action', '1970s', '자영업자', 3.7729430379746836),
 ('Action', '1970s', '전문직', 3.918044077134986),
 ('Action', '1980s', 'CEO', 3.6766459305339554),
 ('Action', '1980s', '교육', nan),
 ('Action', '1980s', '기타', 3.6103782840946255),
 ('Action', '1980s', '농부', 3.3628048780487805),
 ('Action', '1980s', '미성년자', 3.7861328125),
 ('Action', '1980s', '비급여', 3.6990511958885155),
 ('Action', '1980s', '예술', 3.579264426125555),
 ('Action', '1980s', '이공계_직장인', 3.747347585114806),
 ('Action', '1980s', '인문계_직장인', 3.6812840355402696),
 ('Action', '1980s', '자영업자', 3.644341801385681),
 ('Action', '1980s', '전문직', 3.684749515637974),
 ('Action', '1990s', 'CEO', 3.400122967618527),
 ('Action', '1990s', '교육', nan),
 ('Action', '1990s', '기타', 3.231976313841599),
 ('Action', '1990s', '농부', 3.4682926829268292),
 ('Action', '1990s', '미성년자', 3.345362134688691),
 ('Action', '1990s', '비급여', 3.28664142779881),
 ('Action', '1990s', '예술', 3.180047694753577),
 ('Action', '1990s', '이공계_직장인', 3.393534757653061),
 ('Action', '1990s', '인문계_직장인', 3.3525528761956083),
 ('Action', '1990s', '자영업자', 3.336441086642019),
 ('Action', '1990s', '전문직', 3.353355852548098),
 ('Action', '2000s', 'CEO', 3.503076923076923),
 ('Action', '2000s', '교육', nan),
 ('Action', '2000s', '기타', 3.416883116883117),
 ('Action', '2000s', '농부', 3.5),
 ('Action', '2000s', '미성년자', 3.555984555984556),
 ('Action', '2000s', '비급여', 3.506509869802604),
 ('Action', '2000s', '예술', 3.173164097914778),
 ('Action', '2000s', '이공계_직장인', 3.5350588235294116),
 ('Action', '2000s', '인문계_직장인', 3.596170583115753),
 ('Action', '2000s', '자영업자', 3.4751908396946565),
 ('Action', '2000s', '전문직', 3.451718494271686),
 ('Adventure', '1910s', 'CEO', nan),
 ('Adventure', '1910s', '교육', nan),
 ('Adventure', '1910s', '기타', 4.0),
 ('Adventure', '1910s', '농부', nan),
 ('Adventure', '1910s', '미성년자', nan),
 ('Adventure', '1910s', '비급여', 2.0),
 ('Adventure', '1910s', '예술', nan),
 ('Adventure', '1910s', '이공계_직장인', nan),
 ('Adventure', '1910s', '인문계_직장인', 2.0),
 ('Adventure', '1910s', '자영업자', nan),
 ('Adventure', '1910s', '전문직', nan),
 ('Adventure', '1920s', 'CEO', 3.0),
 ('Adventure', '1920s', '교육', nan),
 ('Adventure', '1920s', '기타', 4.0),
 ('Adventure', '1920s', '농부', nan),
 ('Adventure', '1920s', '미성년자', nan),
 ('Adventure', '1920s', '비급여', 3.0),
 ('Adventure', '1920s', '예술', 3.6666666666666665),
 ('Adventure', '1920s', '이공계_직장인', nan),
 ('Adventure', '1920s', '인문계_직장인', 3.0),
 ('Adventure', '1920s', '자영업자', 5.0),
 ('Adventure', '1920s', '전문직', nan),
 ('Adventure', '1930s', 'CEO', 3.986072423398329),
 ('Adventure', '1930s', '교육', nan),
 ('Adventure', '1930s', '기타', 3.9787735849056602),
 ('Adventure', '1930s', '농부', 4.3),
 ('Adventure', '1930s', '미성년자', 3.91025641025641),
 ('Adventure', '1930s', '비급여', 3.904),
 ('Adventure', '1930s', '예술', 4.126344086021505),
 ('Adventure', '1930s', '이공계_직장인', 4.058700209643606),
 ('Adventure', '1930s', '인문계_직장인', 4.066666666666666),
 ('Adventure', '1930s', '자영업자', 4.177514792899408),
 ('Adventure', '1930s', '전문직', 4.015151515151516),
 ('Adventure', '1940s', 'CEO', 3.757575757575758),
 ('Adventure', '1940s', '교육', nan),
 ('Adventure', '1940s', '기타', 3.8402366863905324),
 ('Adventure', '1940s', '농부', 3.25),
 ('Adventure', '1940s', '미성년자', 4.105263157894737),
 ('Adventure', '1940s', '비급여', 3.8582089552238807),
 ('Adventure', '1940s', '예술', 3.7209302325581395),
 ('Adventure', '1940s', '이공계_직장인', 3.8968253968253967),
 ('Adventure', '1940s', '인문계_직장인', 4.170731707317073),
 ('Adventure', '1940s', '자영업자', 3.8636363636363638),
 ('Adventure', '1940s', '전문직', 3.7160493827160495),
 ('Adventure', '1950s', 'CEO', 3.9269406392694064),
 ('Adventure', '1950s', '교육', nan),
 ('Adventure', '1950s', '기타', 3.8676789587852496),
 ('Adventure', '1950s', '농부', 3.3846153846153846),
 ('Adventure', '1950s', '미성년자', 3.5918367346938775),
 ('Adventure', '1950s', '비급여', 3.863741339491917),
 ('Adventure', '1950s', '예술', 3.9585798816568047),
 ('Adventure', '1950s', '이공계_직장인', 3.9945454545454546),
 ('Adventure', '1950s', '인문계_직장인', 3.954861111111111),
 ('Adventure', '1950s', '자영업자', 3.960591133004926),
 ('Adventure', '1950s', '전문직', 3.9567099567099566),
 ('Adventure', '1960s', 'CEO', 3.8805970149253732),
 ('Adventure', '1960s', '교육', nan),
 ('Adventure', '1960s', '기타', 3.8538587848932675),
 ('Adventure', '1960s', '농부', 3.6923076923076925),
 ('Adventure', '1960s', '미성년자', 3.789473684210526),
 ('Adventure', '1960s', '비급여', 3.8134453781512607),
 ('Adventure', '1960s', '예술', 3.8484848484848486),
 ('Adventure', '1960s', '이공계_직장인', 3.8266331658291457),
 ('Adventure', '1960s', '인문계_직장인', 3.872093023255814),
 ('Adventure', '1960s', '자영업자', 3.8118466898954706),
 ('Adventure', '1960s', '전문직', 3.834375),
 ('Adventure', '1970s', 'CEO', 3.747261345852895),
 ('Adventure', '1970s', '교육', nan),
 ('Adventure', '1970s', '기타', 3.71656050955414),
 ('Adventure', '1970s', '농부', 3.6176470588235294),
 ('Adventure', '1970s', '미성년자', 3.7246963562753037),
 ('Adventure', '1970s', '비급여', 3.7107674684994274),
 ('Adventure', '1970s', '예술', 3.640312771503041),
 ('Adventure', '1970s', '이공계_직장인', 3.7619277108433735),
 ('Adventure', '1970s', '인문계_직장인', 3.7899910634495084),
 ('Adventure', '1970s', '자영업자', 3.7022900763358777),
 ('Adventure', '1970s', '전문직', 3.743333333333333),
 ('Adventure', '1980s', 'CEO', 3.580674734140081),
 ('Adventure', '1980s', '교육', nan),
 ('Adventure', '1980s', '기타', 3.5390183871434777),
 ('Adventure', '1980s', '농부', 3.3574468085106384),
 ('Adventure', '1980s', '미성년자', 3.7004264392324093),
 ('Adventure', '1980s', '비급여', 3.6410818713450293),
 ('Adventure', '1980s', '예술', 3.5372393247269116),
 ('Adventure', '1980s', '이공계_직장인', 3.6824016563147),
 ('Adventure', '1980s', '인문계_직장인', 3.618283726323927),
 ('Adventure', '1980s', '자영업자', 3.552486187845304),
 ('Adventure', '1980s', '전문직', 3.5958549222797926),
 ('Adventure', '1990s', 'CEO', 3.302039381153305),
 ('Adventure', '1990s', '교육', nan),
 ('Adventure', '1990s', '기타', 3.197126991791405),
 ('Adventure', '1990s', '농부', 3.360189573459716),
 ('Adventure', '1990s', '미성년자', 3.2543142597638512),
 ('Adventure', '1990s', '비급여', 3.1939416674481853),
 ('Adventure', '1990s', '예술', 3.073058485139022),
 ('Adventure', '1990s', '이공계_직장인', 3.3603281853281852),
 ('Adventure', '1990s', '인문계_직장인', 3.3059611750558324),
 ('Adventure', '1990s', '자영업자', 3.3300198807157058),
 ('Adventure', '1990s', '전문직', 3.313746826260428),
 ('Adventure', '2000s', 'CEO', 3.1075697211155378),
 ('Adventure', '2000s', '교육', nan),
 ('Adventure', '2000s', '기타', 3.054421768707483),
 ('Adventure', '2000s', '농부', 3.125),
 ('Adventure', '2000s', '미성년자', 3.076923076923077),
 ('Adventure', '2000s', '비급여', 3.0429864253393664),
 ('Adventure', '2000s', '예술', 2.9299065420560746),
 ('Adventure', '2000s', '이공계_직장인', 3.092964824120603),
 ('Adventure', '2000s', '인문계_직장인', 3.2146118721461185),
 ('Adventure', '2000s', '자영업자', 3.134020618556701),
 ('Adventure', '2000s', '전문직', 3.05),
 ('Animation', '1910s', 'CEO', nan),
 ('Animation', '1910s', '교육', nan),
 ('Animation', '1910s', '기타', nan),
 ('Animation', '1910s', '농부', nan),
 ('Animation', '1910s', '미성년자', nan),
 ('Animation', '1910s', '비급여', nan),
 ('Animation', '1910s', '예술', nan),
 ('Animation', '1910s', '이공계_직장인', nan),
 ('Animation', '1910s', '인문계_직장인', nan),
 ('Animation', '1910s', '자영업자', nan),
 ('Animation', '1910s', '전문직', nan),
 ('Animation', '1920s', 'CEO', nan),
 ('Animation', '1920s', '교육', nan),
 ('Animation', '1920s', '기타', nan),
 ('Animation', '1920s', '농부', nan),
 ('Animation', '1920s', '미성년자', nan),
 ('Animation', '1920s', '비급여', nan),
 ('Animation', '1920s', '예술', nan),
 ('Animation', '1920s', '이공계_직장인', nan),
 ('Animation', '1920s', '인문계_직장인', nan),
 ('Animation', '1920s', '자영업자', nan),
 ('Animation', '1920s', '전문직', nan),
 ('Animation', '1930s', 'CEO', 3.972972972972973),
 ('Animation', '1930s', '교육', nan),
 ('Animation', '1930s', '기타', 3.8294573643410854),
 ('Animation', '1930s', '농부', 3.6666666666666665),
 ('Animation', '1930s', '미성년자', 3.3823529411764706),
 ('Animation', '1930s', '비급여', 3.645714285714286),
 ('Animation', '1930s', '예술', 3.9263157894736844),
 ('Animation', '1930s', '이공계_직장인', 3.845528455284553),
 ('Animation', '1930s', '인문계_직장인', 3.869047619047619),
 ('Animation', '1930s', '자영업자', 4.0),
 ('Animation', '1930s', '전문직', 3.740740740740741),
 ('Animation', '1940s', 'CEO', 3.8214285714285716),
 ('Animation', '1940s', '교육', nan),
 ('Animation', '1940s', '기타', 3.7131147540983607),
 ('Animation', '1940s', '농부', 3.375),
 ('Animation', '1940s', '미성년자', 3.5348837209302326),
 ('Animation', '1940s', '비급여', 3.64274322169059),
 ('Animation', '1940s', '예술', 3.699208443271768),
 ('Animation', '1940s', '이공계_직장인', 3.732876712328767),
 ('Animation', '1940s', '인문계_직장인', 3.7955271565495208),
 ('Animation', '1940s', '자영업자', 3.8551724137931034),
 ('Animation', '1940s', '전문직', 3.7091836734693877),
 ('Animation', '1950s', 'CEO', 3.8564814814814814),
 ('Animation', '1950s', '교육', nan),
 ('Animation', '1950s', '기타', 3.7724137931034485),
 ('Animation', '1950s', '농부', 3.6666666666666665),
 ('Animation', '1950s', '미성년자', 3.4210526315789473),
 ('Animation', '1950s', '비급여', 3.751987281399046),
 ('Animation', '1950s', '예술', 3.657303370786517),
 ('Animation', '1950s', '이공계_직장인', 3.71356783919598),
 ('Animation', '1950s', '인문계_직장인', 3.8504983388704317),
 ('Animation', '1950s', '자영업자', 3.7007874015748032),
 ('Animation', '1950s', '전문직', 3.68),
 ('Animation', '1960s', 'CEO', 3.768041237113402),
 ('Animation', '1960s', '교육', nan),
 ('Animation', '1960s', '기타', 3.80718954248366),
 ('Animation', '1960s', '농부', 3.625),
 ('Animation', '1960s', '미성년자', 3.505050505050505),
 ('Animation', '1960s', '비급여', 3.624),
 ('Animation', '1960s', '예술', 3.7653846153846153),
 ('Animation', '1960s', '이공계_직장인', 3.7096774193548385),
 ('Animation', '1960s', '인문계_직장인', 3.9530516431924885),
 ('Animation', '1960s', '자영업자', 3.6770833333333335),
 ('Animation', '1960s', '전문직', 3.8403361344537816),
 ('Animation', '1970s', 'CEO', 3.507936507936508),
 ('Animation', '1970s', '교육', nan),
 ('Animation', '1970s', '기타', 3.518134715025907),
 ('Animation', '1970s', '농부', 3.3076923076923075),
 ('Animation', '1970s', '미성년자', 3.4146341463414633),
 ('Animation', '1970s', '비급여', 3.5331858407079646),
 ('Animation', '1970s', '예술', 3.4901960784313726),
 ('Animation', '1970s', '이공계_직장인', 3.579081632653061),
 ('Animation', '1970s', '인문계_직장인', 3.698744769874477),
 ('Animation', '1970s', '자영업자', 3.5434782608695654),
 ('Animation', '1970s', '전문직', 3.5185185185185186),
 ('Animation', '1980s', 'CEO', 3.5422680412371133),
 ('Animation', '1980s', '교육', nan),
 ('Animation', '1980s', '기타', 3.5407673860911273),
 ('Animation', '1980s', '농부', 3.1923076923076925),
 ('Animation', '1980s', '미성년자', 3.435185185185185),
 ('Animation', '1980s', '비급여', 3.612876935615322),
 ('Animation', '1980s', '예술', 3.6289592760180995),
 ('Animation', '1980s', '이공계_직장인', 3.6464354527938343),
 ('Animation', '1980s', '인문계_직장인', 3.6502546689303905),
 ('Animation', '1980s', '자영업자', 3.574162679425837),
 ('Animation', '1980s', '전문직', 3.6233333333333335),
 ('Animation', '1990s', 'CEO', 3.76027397260274),
 ('Animation', '1990s', '교육', nan),
 ('Animation', '1990s', '기타', 3.7332896461336826),
 ('Animation', '1990s', '농부', 3.7096774193548385),
 ('Animation', '1990s', '미성년자', 3.5116841257050764),
 ('Animation', '1990s', '비급여', 3.6864462447996496),
 ('Animation', '1990s', '예술', 3.7157339821573396),
 ('Animation', '1990s', '이공계_직장인', 3.819258089976322),
 ('Animation', '1990s', '인문계_직장인', 3.833574529667149),
 ('Animation', '1990s', '자영업자', 3.817042606516291),
 ('Animation', '1990s', '전문직', 3.7622739018087854),
 ('Animation', '2000s', 'CEO', 3.3633217993079585),
 ('Animation', '2000s', '교육', nan),
 ('Animation', '2000s', '기타', 3.3730886850152904),
 ('Animation', '2000s', '농부', 3.5),
 ('Animation', '2000s', '미성년자', 3.164705882352941),
 ('Animation', '2000s', '비급여', 3.3806921675774135),
 ('Animation', '2000s', '예술', 3.297202797202797),
 ('Animation', '2000s', '이공계_직장인', 3.4904580152671754),
 ('Animation', '2000s', '인문계_직장인', 3.4419642857142856),
 ('Animation', '2000s', '자영업자', 3.36697247706422),
 ('Animation', '2000s', '전문직', 3.3642384105960264),
 ("Children's", '1910s', 'CEO', nan),
 ("Children's", '1910s', '교육', nan),
 ("Children's", '1910s', '기타', nan),
 ("Children's", '1910s', '농부', nan),
 ("Children's", '1910s', '미성년자', nan),
 ("Children's", '1910s', '비급여', nan),
 ("Children's", '1910s', '예술', nan),
 ("Children's", '1910s', '이공계_직장인', nan),
 ("Children's", '1910s', '인문계_직장인', nan),
 ("Children's", '1910s', '자영업자', nan),
 ("Children's", '1910s', '전문직', nan),
 ("Children's", '1920s', 'CEO', nan),
 ("Children's", '1920s', '교육', nan),
 ("Children's", '1920s', '기타', nan),
 ("Children's", '1920s', '농부', nan),
 ("Children's", '1920s', '미성년자', nan),
 ("Children's", '1920s', '비급여', nan),
 ("Children's", '1920s', '예술', nan),
 ("Children's", '1920s', '이공계_직장인', nan),
 ("Children's", '1920s', '인문계_직장인', nan),
 ("Children's", '1920s', '자영업자', nan),
 ("Children's", '1920s', '전문직', nan),
 ("Children's", '1930s', 'CEO', 4.1484375),
 ("Children's", '1930s', '교육', nan),
 ("Children's", '1930s', '기타', 4.049586776859504),
 ("Children's", '1930s', '농부', 4.25),
 ("Children's", '1930s', '미성년자', 3.7865168539325844),
 ("Children's", '1930s', '비급여', 3.8856548856548856),
 ("Children's", '1930s', '예술', 4.203947368421052),
 ("Children's", '1930s', '이공계_직장인', 4.0954773869346734),
 ("Children's", '1930s', '인문계_직장인', 4.170454545454546),
 ("Children's", '1930s', '자영업자', 4.228070175438597),
 ("Children's", '1930s', '전문직', 4.145695364238411),
 ("Children's", '1940s', 'CEO', 3.77037037037037),
 ("Children's", '1940s', '교육', nan),
 ("Children's", '1940s', '기타', 3.6806883365200767),
 ("Children's", '1940s', '농부', 3.3333333333333335),
 ("Children's", '1940s', '미성년자', 3.5407407407407407),
 ("Children's", '1940s', '비급여', 3.6248062015503875),
 ("Children's", '1940s', '예술', 3.6733668341708543),
 ("Children's", '1940s', '이공계_직장인', 3.69281045751634),
 ("Children's", '1940s', '인문계_직장인', 3.79375),
 ("Children's", '1940s', '자영업자', 3.8376623376623376),
 ("Children's", '1940s', '전문직', 3.656862745098039),
 ("Children's", '1950s', 'CEO', 3.7745664739884393),
 ("Children's", '1950s', '교육', nan),
 ("Children's", '1950s', '기타', 3.710144927536232),
 ("Children's", '1950s', '농부', 3.6363636363636362),
 ("Children's", '1950s', '미성년자', 3.380434782608696),
 ("Children's", '1950s', '비급여', 3.703794369645043),
 ("Children's", '1950s', '예술', 3.635593220338983),
 ("Children's", '1950s', '이공계_직장인', 3.689655172413793),
 ("Children's", '1950s', '인문계_직장인', 3.7858942065491186),
 ("Children's", '1950s', '자영업자', 3.665),
 ("Children's", '1950s', '전문직', 3.6706349206349205),
 ("Children's", '1960s', 'CEO', 3.63302752293578),
 ("Children's", '1960s', '교육', nan),
 ("Children's", '1960s', '기타', 3.6874074074074072),
 ("Children's", '1960s', '농부', 2.8125),
 ("Children's", '1960s', '미성년자', 3.504950495049505),
 ("Children's", '1960s', '비급여', 3.601965601965602),
 ("Children's", '1960s', '예술', 3.5233265720081137),
 ("Children's", '1960s', '이공계_직장인', 3.678843226788432),
 ("Children's", '1960s', '인문계_직장인', 3.7510822510822512),
 ("Children's", '1960s', '자영업자', 3.495),
 ("Children's", '1960s', '전문직', 3.678030303030303),
 ("Children's", '1970s', 'CEO', 3.425431711145997),
 ("Children's", '1970s', '교육', nan),
 ("Children's", '1970s', '기타', 3.487378640776699),
 ("Children's", '1970s', '농부', 3.4615384615384617),
 ("Children's", '1970s', '미성년자', 3.416),
 ("Children's", '1970s', '비급여', 3.44752308984047),
 ("Children's", '1970s', '예술', 3.4393358876117497),
 ("Children's", '1970s', '이공계_직장인', 3.469043151969981),
 ("Children's", '1970s', '인문계_직장인', 3.57856093979442),
 ("Children's", '1970s', '자영업자', 3.2857142857142856),
 ("Children's", '1970s', '전문직', 3.4354354354354353),
 ("Children's", '1980s', 'CEO', 3.382136279926335),
 ("Children's", '1980s', '교육', nan),
 ("Children's", '1980s', '기타', 3.4469472436277417),
 ("Children's", '1980s', '농부', 3.087719298245614),
 ("Children's", '1980s', '미성년자', 3.331742243436754),
 ("Children's", '1980s', '비급여', 3.5105535643170054),
 ("Children's", '1980s', '예술', 3.416795069337442),
 ("Children's", '1980s', '이공계_직장인', 3.464816650148662),
 ("Children's", '1980s', '인문계_직장인', 3.5482189400521285),
 ("Children's", '1980s', '자영업자', 3.375586854460094),
 ("Children's", '1980s', '전문직', 3.5052447552447554),
 ("Children's", '1990s', 'CEO', 3.3217537942664417),
 ("Children's", '1990s', '교육', nan),
 ("Children's", '1990s', '기타', 3.2947122861586315),
 ("Children's", '1990s', '농부', 3.1875),
 ("Children's", '1990s', '미성년자', 3.1196269261962692),
 ("Children's", '1990s', '비급여', 3.167191134218087),
 ("Children's", '1990s', '예술', 3.176937825253355),
 ("Children's", '1990s', '이공계_직장인', 3.3794921875),
 ("Children's", '1990s', '인문계_직장인', 3.4229224590670375),
 ("Children's", '1990s', '자영업자', 3.3717647058823528),

In [9]:
result = pd.DataFrame(values)
result.columns = ['genres','ages','occupation','rating_mean']    # 각각 i,j,a,x 
result

       genres   ages occupation  rating_mean
0      Action  1910s        CEO          NaN
1      Action  1910s         교육          NaN
2      Action  1910s         기타          NaN
3      Action  1910s         농부          NaN
4      Action  1910s       미성년자          NaN
...       ...    ...        ...          ...
1975  Western  2000s         예술          NaN
1976  Western  2000s    이공계_직장인          NaN
1977  Western  2000s    인문계_직장인          NaN
1978  Western  2000s       자영업자          NaN
1979  Western  2000s        전문직          NaN

[1980 rows x 4 columns]

In [10]:
result_pivot = pd.pivot_table(result,                # 피벗할 데이터프레임
                     index = ['ages','occupation'],    # 행 위치에 들어갈 열
                     columns = 'genres',    # 열 위치에 들어갈 열
                     values = 'rating_mean')
result_pivot

genres              Action  Adventure  Animation  Children's    Comedy  \
ages  occupation
1910s CEO              NaN        NaN        NaN         NaN  3.500000
      기타               NaN   4.000000        NaN         NaN  4.000000
      비급여         5.000000   2.000000        NaN         NaN  3.200000
      예술          3.000000        NaN        NaN         NaN  3.285714
      이공계_직장인          NaN        NaN        NaN         NaN  5.000000
...                    ...        ...        ...         ...       ...
2000s 인문계_직장인     3.596171   3.214612   3.441964    3.333333  3.418455
      자영업자        3.475191   3.134021   3.366972    3.372340  3.524370
      전문직         3.451718   3.050000   3.364238    3.158621  3.385501
      농부          3.500000   3.125000   3.500000    3.333333  3.409091
      미성년자        3.555985   3.076923   3.164706    3.034965  3.321522

genres               Crime  Documentary     Drama   Fantasy  Film-Noir  \
ages  occupation
1910s CEO              NaN          NaN       NaN       NaN        NaN
      기타               NaN          NaN  4.000000       NaN        NaN
      비급여              NaN          NaN  3.500000       NaN        NaN
      예술               NaN          NaN  3.000000       NaN        NaN
      이공계_직장인          NaN          NaN       NaN       NaN        NaN
...                    ...          ...       ...       ...        ...
2000s 인문계_직장인     3.217617     3.725000  3.741686  2.700000        NaN
      자영업자        3.365854     3.666667  3.783203  2.125000        NaN
      전문직         3.159574     3.142857  3.638158  2.250000        NaN
      농부          3.333333          NaN  3.428571       NaN        NaN
      미성년자        3.319588     2.812500  3.581513  2.571429        NaN

genres              Horror  Musical   Mystery   Romance    Sci-Fi  Thriller  \
ages  occupation
1910s CEO              NaN      NaN       NaN       NaN       NaN       NaN
      기타               NaN      NaN       NaN       NaN       NaN       NaN
      비급여              NaN      NaN       NaN       NaN       NaN       NaN
      예술               NaN      NaN       NaN       NaN       NaN       NaN
      이공계_직장인          NaN      NaN       NaN       NaN       NaN       NaN
...                    ...      ...       ...       ...       ...       ...
2000s 인문계_직장인     2.900415     3.50  2.863636  3.293023  3.271154  3.352821
      자영업자        2.850746     2.80  2.916667  3.500000  3.088372  3.330827
      전문직         3.065217     3.75  3.090909  3.316176  3.069231  3.311111
      농부          2.500000     3.00       NaN  2.666667  3.055556  3.047619
      미성년자        3.141791     3.60  3.181818  3.125000  3.247387  3.376842

genres                 War  Western
ages  occupation
1910s CEO              NaN      NaN
      기타               NaN      NaN
      비급여              NaN      NaN
      예술               NaN      NaN
      이공계_직장인          NaN      NaN
...                    ...      ...
2000s 인문계_직장인     3.825758      NaN
      자영업자        3.946429      NaN
      전문직         3.984375      NaN
      농부          4.500000      NaN
      미성년자        3.888889      NaN

[98 rows x 18 columns]

In [ ]:
result_pivot.to_excel("result_job_2.xlsx")